#ifndef __ERRORS_H__
#define __ERRORS_H__

#define ERR_OK 0
#define ERR_UNKNOWN -1
#define ERR_WRONG_FILENAME 2
#define ERR_ARGS_COUNT 3
#define ERR_ARGS_KEY 4
#define ERR_FILE_EMPTY 5
#define ERR_MALLOC 6
#define ERR_FILTER 7

#define ERR_READ 100
#define ERR_READ_NAME 101
#define ERR_READ_PERFORMANCE 102
#define ERR_READ_PRODUCER 103
#define ERR_READ_MIN_PRICE 104
#define ERR_READ_MAX_PRICE 105
#define ERR_READ_TYPE_ID 106
#define ERR_READ_KID_AGE 107
#define ERR_READ_KID_GENRE 108
#define ERR_READ_ADULT_GENRE 109
#define ERR_READ_MUSIC_COMPOSER 110
#define ERR_READ_MUSIC_COUNTRY 111
#define ERR_READ_MUSIC_MIN_AGE 112
#define ERR_READ_MUSIC_DURATION 113

#define ERR_TABLE_OVERFLOW 120

#endif // #ifndef __ERRORS_H__
